# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-17 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, default='')),
                ('content_length', models.TextField(blank=True, default='')),
            ],
        ),
    ]
