# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidercontent',
            name='category',
            field=models.TextField(default='n/a'),
        ),
    ]
